---
- name: Install WireGuard
  become: true
  apt:
    name: wireguard
    state: present
    update_cache: true

- name: Enable IP forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Generate WireGuard server keys
  become: true
  command: "/usr/bin/wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey"
  creates: /etc/wireguard/privatekey

- name: Configure WireGuard interface
  become: true
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0600

- name: Start WireGuard service
  become: true
  systemd:
    name: wg-quick@wg0
    enabled: true
    state: started
