---
- name: Create NGINX configuration directory
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: Deploy NGINX Docker container with multiple domain support
  docker_container:
    name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d      # NGINX config files
      - ./nginx/ssl:/etc/letsencrypt           # SSL certificates from Certbot
    restart_policy: always

- name: Deploy multi-host NGINX configuration
  template:
    src: nginx-multi-host.conf.j2
    dest: ./nginx/conf.d/multi-host.conf
    mode: '0644'

- name: Restart NGINX container
  docker_container:
    name: nginx
    state: restarted
