version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./html:/usr/share/nginx/html  # Serve the index.html file
      - ./conf:/etc/nginx/conf.d       # Nginx configuration
      - /etc/letsencrypt:/etc/letsencrypt  # LetsEncrypt certificates
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    depends_on:
      - certbot
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"

networks:
  web:
