---
- name: Create directory for SSL certificates
  file:
    path: /etc/letsencrypt
    state: directory

- name: Deploy Certbot Docker container
  docker_container:
    name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt  # Share SSL certs with NGINX
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    restart_policy: always

- name: Obtain SSL certificates for domains
  command: >
    docker run --rm --name certbot certbot/certbot certonly --webroot -w /var/www/certbot
    -d {{ item.domain_name }} --email admin@{{ item.domain_name }} --agree-tos --no-eff-email
  with_items: "{{ nginx_multi_hosts }}"
  register: certbot_result

- name: Restart NGINX to load SSL certificates
  docker_container:
    name: nginx
    state: restarted
  when: certbot_result is changed
