name: Deploy and Manage Hetzner VM with Ansible

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Create terraform.auto.tfvars
        run: |
          cat <<EOF > terraform/terraform.auto.tfvars
          hcloud_token = "${{ secrets.HCLOUD_TOKEN }}"
          ssh_key_name = "${{ secrets.SSH_KEY_NAME }}"
          ssh_public_key = "${{ secrets.SSH_PUBLIC_KEY }}"
          firewall_name = "firewall-1"
          EOF

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get Terraform Output (Public IP)
        id: terraform_output
        run: |
          public_ip=$(terraform output -raw public_ip 2>/dev/null)
          echo "Raw output: $public_ip"

          if [ -z "$public_ip" ]; then
            echo "No output received from Terraform for public_ip."
            exit 1
          fi

          echo "public_ip=$public_ip" >> $GITHUB_OUTPUT
        working-directory: ./terraform


  ansible:
    name: Configure VM with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Add Private SSH Key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          ANSIBLE_SSH_PRIVATE_KEY_FILE: ~/.ssh/id_rsa

      - name: Update Ansible Inventory with Public IP
        run: |
          sed -i "s/{{ public_ip }}/${{ needs.terraform.outputs.public_ip }}/g" inventory.yml
        working-directory: ./ansible

      - name: Check Ansible Inventory
        run: cat ansible/inventory.yml
        working-directory: ./ansible

      - name: Run Ansible Playbook with Debugging
        run: ansible-playbook -i inventory.yml playbook.yml -vvvv
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        working-directory: ./ansible
