name: Deploy Hetzner VM with Terraform

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    outputs:
      public_ip: ${{ steps.get_ip.outputs.public_ip }}  # Output the public IP from the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Create terraform.auto.tfvars
        run: |
          cat <<EOF > terraform/terraform.auto.tfvars
          hcloud_token = "${{ secrets.HCLOUD_TOKEN }}"
          ssh_key_name = "${{ secrets.SSH_KEY_NAME }}"
          ssh_public_key = "${{ secrets.SSH_PUBLIC_KEY }}"
          sudo_user = "${{ secrets.SUDO_USER }}"
          firewall_name = "firewall-1"
          EOF

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - id: get_ip  # Capture public IP in this step
        name: Get Terraform Output (Public IP)
        run: |
          public_ip=$(terraform output -raw public_ip)
          echo "Public IP from Terraform: $public_ip"
          echo "public_ip=$public_ip" >> $GITHUB_OUTPUT
        working-directory: ./terraform

      # Store public IP in GitHub Environment or as a secret
      - name: Save public IP to environment file
        run: echo "PUBLIC_IP=$public_ip" >> $GITHUB_ENV
